# Generated by Django 4.2.7 on 2025-08-24 23:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Landing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                (
                    "domain",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="Домен",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("inactive", "Неактивен"),
                            ("maintenance", "Техобслуживание"),
                            ("draft", "Черновик"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("config", models.JSONField(default=dict, verbose_name="Конфигурация")),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("default", "Стандартная"),
                            ("modern", "Современная"),
                            ("minimal", "Минималистичная"),
                            ("corporate", "Корпоративная"),
                            ("creative", "Креативная"),
                        ],
                        default="default",
                        max_length=20,
                        verbose_name="Тема",
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="UTM Source"
                    ),
                ),
                (
                    "utm_medium",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="UTM Medium"
                    ),
                ),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="UTM Campaign"
                    ),
                ),
                (
                    "visitors_today",
                    models.IntegerField(default=0, verbose_name="Посетители сегодня"),
                ),
                (
                    "visitors_total",
                    models.IntegerField(default=0, verbose_name="Всего посетителей"),
                ),
                (
                    "conversions_today",
                    models.IntegerField(default=0, verbose_name="Конверсии сегодня"),
                ),
                (
                    "conversions_total",
                    models.IntegerField(default=0, verbose_name="Всего конверсий"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лендинг",
                "verbose_name_plural": "Лендинги",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LandingAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("visitors", models.IntegerField(default=0, verbose_name="Посетители")),
                (
                    "unique_visitors",
                    models.IntegerField(
                        default=0, verbose_name="Уникальные посетители"
                    ),
                ),
                (
                    "page_views",
                    models.IntegerField(default=0, verbose_name="Просмотры страниц"),
                ),
                (
                    "conversions",
                    models.IntegerField(default=0, verbose_name="Конверсии"),
                ),
                ("leads", models.IntegerField(default=0, verbose_name="Лиды")),
                (
                    "avg_session_duration",
                    models.FloatField(
                        default=0, verbose_name="Средняя длительность сессии"
                    ),
                ),
                (
                    "bounce_rate",
                    models.FloatField(default=0, verbose_name="Процент отказов"),
                ),
                (
                    "organic_traffic",
                    models.IntegerField(default=0, verbose_name="Органический трафик"),
                ),
                (
                    "paid_traffic",
                    models.IntegerField(default=0, verbose_name="Платный трафик"),
                ),
                (
                    "direct_traffic",
                    models.IntegerField(default=0, verbose_name="Прямой трафик"),
                ),
                (
                    "referral_traffic",
                    models.IntegerField(default=0, verbose_name="Реферальный трафик"),
                ),
                ("utm_data", models.JSONField(default=dict, verbose_name="UTM данные")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "landing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="landings.landing",
                        verbose_name="Лендинг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аналитика лендинга",
                "verbose_name_plural": "Аналитика лендингов",
                "ordering": ["-date"],
                "unique_together": {("landing", "date")},
            },
        ),
    ]
