version: "3.9"

services:
  backend:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-your-repo}-backend:${TAG:-latest}
    container_name: asia-backend-prod
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=WARNING
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-your-repo}-frontend:${TAG:-latest}
    container_name: asia-frontend-prod
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.${DOMAIN:-yourdomain.com}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15
    container_name: asia-db-prod
    environment:
      POSTGRES_USER: ${DB_USER:-asia}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-asia}
      POSTGRES_DB: ${DB_NAME:-asia_crm}
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-asia} -d ${DB_NAME:-asia_crm}"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: asia-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: asia-redis-prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  pgdata_prod:
  redis_data:
