version: "3.9"

services:
  backend:
    build: ./backend
    container_name: asia-backend-staging
    ports:
      - "8001:8000"
    environment:
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO
      - DB_URL=postgresql://asia:asia@db:5432/asia_crm_staging
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-staging-secret-key
      - JWT_SECRET=your-staging-jwt-secret
      - AMOCRM_CLIENT_ID=
      - AMOCRM_CLIENT_SECRET=
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: asia-db-staging
    environment:
      POSTGRES_USER: asia
      POSTGRES_PASSWORD: asia
      POSTGRES_DB: asia_crm_staging
    volumes:
      - pgdata_staging:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: asia-redis-staging
    ports:
      - "6380:6379"
    volumes:
      - redis_data_staging:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  pgdata_staging:
  redis_data_staging:
