version: "3.9"

services:
  backend:
    build: ./backend
    container_name: asia-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: asia-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: asia-db
    environment:
      POSTGRES_USER: asia
      POSTGRES_PASSWORD: asia
      POSTGRES_DB: asia_crm
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  metabase:
    image: metabase/metabase:latest
    container_name: asia-metabase
    ports:
      - "3001:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_DB_TYPE: h2
    volumes:
      - ./analytics/dashboards:/metabase-data
    restart: unless-stopped
    depends_on:
      - db

volumes:
  pgdata:
