version: "3.9"

services:
  backend:
    build: ./backend
    container_name: asia-backend-staging
    ports:
      - "${BACKEND_PORT:-8001}:8000"
    env_file:
      - .env.staging
    environment:
      - ENVIRONMENT=staging
      - PYTHONPATH=/app
    depends_on:
      - db
      - redis
    restart: unless-stopped
    volumes:
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15
    container_name: asia-db-staging
    env_file:
      - .env.staging
    environment:
      POSTGRES_USER: ${DB_USER:-asia}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-asia}
      POSTGRES_DB: ${DB_NAME:-asia_crm_staging}
    volumes:
      - pgdata_staging:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5433}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-asia} -d ${DB_NAME:-asia_crm_staging}"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: asia-redis-staging
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - redis_data_staging:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: asia-nginx-staging
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx/nginx-staging.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata_staging:
  redis_data_staging:
