apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: staging
data:
  DATABASE_URL: "postgresql://asia:asia@postgres-service:5432/asia_crm"
  REDIS_URL: "redis://redis-service:6379"
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "staging"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
data:
  DATABASE_URL: "postgresql://asia:asia@postgres-service:5432/asia_crm"
  REDIS_URL: "redis://redis-service:6379"
  LOG_LEVEL: "WARNING"
  ENVIRONMENT: "production"
