# Generated by Django 4.2.7 on 2025-08-24 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("landings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("layout", models.JSONField(default=dict, verbose_name="Макет")),
                ("filters", models.JSONField(default=dict, verbose_name="Фильтры")),
                (
                    "refresh_interval",
                    models.IntegerField(
                        default=300, verbose_name="Интервал обновления (сек)"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Публичный"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_dashboards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Поделено с",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дашборд",
                "verbose_name_plural": "Дашборды",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневный"),
                            ("weekly", "Еженедельный"),
                            ("monthly", "Ежемесячный"),
                            ("quarterly", "Ежеквартальный"),
                            ("yearly", "Ежегодный"),
                            ("custom", "Пользовательский"),
                        ],
                        max_length=20,
                        verbose_name="Тип отчета",
                    ),
                ),
                ("template", models.TextField(blank=True, verbose_name="Шаблон")),
                ("config", models.JSONField(default=dict, verbose_name="Конфигурация")),
                ("filters", models.JSONField(default=dict, verbose_name="Фильтры")),
                (
                    "is_scheduled",
                    models.BooleanField(default=False, verbose_name="По расписанию"),
                ),
                (
                    "schedule_cron",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cron выражение"
                    ),
                ),
                (
                    "last_generated",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последняя генерация"
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                            ("html", "HTML"),
                        ],
                        default="pdf",
                        max_length=10,
                        verbose_name="Формат экспорта",
                    ),
                ),
                (
                    "auto_export",
                    models.BooleanField(default=False, verbose_name="Автоэкспорт"),
                ),
                (
                    "export_recipients",
                    models.JSONField(default=list, verbose_name="Получатели экспорта"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет",
                "verbose_name_plural": "Отчеты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("running", "Выполняется"),
                            ("completed", "Завершен"),
                            ("failed", "Ошибка"),
                            ("cancelled", "Отменен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="Параметры"),
                ),
                ("filters", models.JSONField(default=dict, verbose_name="Фильтры")),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Путь к файлу"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="Размер файла"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Начало выполнения"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершение выполнения"
                    ),
                ),
                (
                    "duration",
                    models.FloatField(default=0, verbose_name="Длительность (сек)"),
                ),
                (
                    "is_scheduled",
                    models.BooleanField(default=False, verbose_name="По расписанию"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="analytics.report",
                        verbose_name="Отчет",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Запустил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выполнение отчета",
                "verbose_name_plural": "Выполнения отчетов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("counter", "Счетчик"),
                            ("gauge", "Индикатор"),
                            ("histogram", "Гистограмма"),
                            ("line_chart", "Линейный график"),
                            ("bar_chart", "Столбчатый график"),
                            ("pie_chart", "Круговая диаграмма"),
                            ("table", "Таблица"),
                        ],
                        max_length=20,
                        verbose_name="Тип метрики",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(max_length=100, verbose_name="Источник данных"),
                ),
                ("query", models.TextField(blank=True, verbose_name="Запрос")),
                ("config", models.JSONField(default=dict, verbose_name="Конфигурация")),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Единица измерения"
                    ),
                ),
                (
                    "format_string",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Формат отображения"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff", max_length=7, verbose_name="Цвет"
                    ),
                ),
                ("filters", models.JSONField(default=dict, verbose_name="Фильтры")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Метрика",
                "verbose_name_plural": "Метрики",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DashboardMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_x",
                    models.IntegerField(default=0, verbose_name="Позиция X"),
                ),
                (
                    "position_y",
                    models.IntegerField(default=0, verbose_name="Позиция Y"),
                ),
                ("width", models.IntegerField(default=6, verbose_name="Ширина")),
                ("height", models.IntegerField(default=4, verbose_name="Высота")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок"
                    ),
                ),
                (
                    "show_title",
                    models.BooleanField(
                        default=True, verbose_name="Показывать заголовок"
                    ),
                ),
                (
                    "refresh_interval",
                    models.IntegerField(
                        default=0, verbose_name="Интервал обновления (сек)"
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="analytics.dashboard",
                        verbose_name="Дашборд",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.metric",
                        verbose_name="Метрика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Метрика дашборда",
                "verbose_name_plural": "Метрики дашборда",
                "unique_together": {("dashboard", "metric")},
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Просмотр страницы"),
                            ("form_submit", "Отправка формы"),
                            ("button_click", "Клик по кнопке"),
                            ("link_click", "Клик по ссылке"),
                            ("scroll", "Прокрутка"),
                            ("time_on_page", "Время на странице"),
                            ("bounce", "Отказ"),
                            ("conversion", "Конверсия"),
                            ("custom", "Пользовательское событие"),
                        ],
                        max_length=20,
                        verbose_name="Тип события",
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(default=dict, verbose_name="Данные события"),
                ),
                ("value", models.FloatField(default=0, verbose_name="Значение")),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID сессии"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID пользователя"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=2, verbose_name="Страна"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Город"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "device_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Тип устройства"
                    ),
                ),
                (
                    "browser",
                    models.CharField(blank=True, max_length=50, verbose_name="Браузер"),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Операционная система"
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="UTM Source"
                    ),
                ),
                (
                    "utm_medium",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="UTM Medium"
                    ),
                ),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="UTM Campaign"
                    ),
                ),
                (
                    "utm_term",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="UTM Term"
                    ),
                ),
                (
                    "utm_content",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="UTM Content"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Временная метка"
                    ),
                ),
                (
                    "landing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landings.landing",
                        verbose_name="Лендинг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие аналитики",
                "verbose_name_plural": "События аналитики",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="analytics_a_timesta_aef2a5_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="analytics_a_event_t_a460ec_idx"
                    ),
                    models.Index(
                        fields=["landing"], name="analytics_a_landing_6a5126_idx"
                    ),
                    models.Index(
                        fields=["session_id"], name="analytics_a_session_8757e5_idx"
                    ),
                    models.Index(
                        fields=["utm_source"], name="analytics_a_utm_sou_5f117a_idx"
                    ),
                    models.Index(
                        fields=["utm_medium"], name="analytics_a_utm_med_fd3b16_idx"
                    ),
                    models.Index(
                        fields=["utm_campaign"], name="analytics_a_utm_cam_4488de_idx"
                    ),
                ],
            },
        ),
    ]
