name: CI
on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements-dev.txt || true
          pip install -r backend/requirements.txt || true
        continue-on-error: true
      - name: Run backend tests
        run: make -s check-backend || true
        continue-on-error: true

  frontend:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - name: Install dependencies
        run: |
          cd frontend
          npm ci || true
        continue-on-error: true
      - name: Run linting
        run: |
          cd frontend
          npm run lint || true
        continue-on-error: true
      - name: Run tests
        run: |
          cd frontend
          npm test --if-present || true
        continue-on-error: true
      - name: Build project
        run: |
          cd frontend
          npm run build || true
        continue-on-error: true

