name: Security Scan

on:
  schedule:
    - cron: '0 2 * * 1'  # Каждый понедельник в 2:00
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Сканирование Python зависимостей
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install safety
      run: pip install safety

    - name: Run safety check
      working-directory: ./backend
      run: safety check --json --output safety-report.json || true

    - name: Upload safety report
      uses: actions/upload-artifact@v3
      with:
        name: safety-report
        path: backend/safety-report.json

    # Сканирование Node.js зависимостей
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install audit-ci
      run: npm install -g audit-ci

    - name: Run npm audit
      working-directory: ./frontend
      run: audit-ci --moderate --report --format json --output audit-report.json || true

    - name: Upload audit report
      uses: actions/upload-artifact@v3
      with:
        name: audit-report
        path: frontend/audit-report.json

    # Сканирование Docker образов
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ github.repository }}-backend:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
